### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mEnacEc** [HuiTeab/EFT-DMA-Radar-Only-Code#1]
have a error alert when i running
<img width="526" alt="image" src="https://github.com/HuiTeab/EFT-DMA-Radar-Only-Code/assets/40492268/785dcaa0-83b2-49ac-9ab2-3d7bd32fe296">

**Comment by mcapala** [comment]
It's probably because you downloaded too new MemProcFS version. You have to use 4.6 https://github.com/ufrisk/MemProcFS/releases/tag/v4.6

**Comment by xx0m** [comment]
This has been discontinued however checkout the repo owners profile as there's a new version available
